parameters:
  policy_dir: '%kernel.project_dir%/policies'

services:
  App\Complying\Repository\CompliancePolicyRepository:
    arguments:
      $policyDir: '%policy_dir%'
    autowire: true
    autoconfigure: true

  App\Complying\Service\ComplianceRealtimeGuard:
    autowire: true
    autoconfigure: true

  App\Complying\Service\Payment\CompliancePaymentGuard:
    autowire: true
    autoconfigure: true
    public: true

  App\Complying\Command\CompliancePolicyLintCommand:
    autowire: true
    autoconfigure: true
    public: true

  App\Complying\Command\ComplianceGuardEvaluateCommand:
    autowire: true
    autoconfigure: true
    public: true
