services:
  App\Complying\Service\ComplianceExternalRiskClient:
    arguments:
      $endpoint: '%env(EXTERNAL_RISK_ENDPOINT)%'
      $timeout: 2.5

  App\Complying\Service\ComplianceExternalRiskScoreService:
    decorates: 'App\Complying\Service\ComplianceRiskScoreService'
    arguments:
      - '@App\Complying\Service\ComplianceExternalRiskScoreService.inner'
      - '@App\Complying\Service\ComplianceExternalRiskClient'
