parameters:
  compliance.role.endpoint: 'https://role.local/policy/decide'

services:
  App\Complying\Service\Policy\ComplianceRolePolicyClient:
    arguments:
      $httpClient: '@http_client'
      $endpoint: '%compliance.role.endpoint%'
  App\Complying\Service\CompliancePolicyEvaluationService:
    autowire: true
    autoconfigure: true
  App\Complying\ServiceInterface\CompliancePolicyEvaluationServiceInterface: '@App\Complying\Service\CompliancePolicyEvaluationService'
