parameters:
  compliance.role.policies_endpoint: 'https://role.local/policy/list'

services:
  App\Complying\Service\CompliancePolicyRegistryService:
    autowire: true
    autoconfigure: true
    arguments:
      $endpoint: '%compliance.role.policies_endpoint%'
