services:
  App\Complying\Service\CompliancePolicyExpressionEvaluator:
    autowire: true
    autoconfigure: true
  App\Complying\Provider\CompliancePolicyExpressionProvider:
    autowire: true
    autoconfigure: true
  App\Complying\Service\ComplianceExpressionAwarePolicyEvaluationService:
    decorates: 'App\Complying\ServiceInterface\CompliancePolicyEvaluationServiceInterface'
    arguments:
      - '@App\Complying\Service\ComplianceExpressionAwarePolicyEvaluationService.inner'
      - '@App\Complying\Provider\CompliancePolicyExpressionProvider'
      - '@App\Complying\Service\CompliancePolicyExpressionEvaluator'
