services:
  App\Complying\Service\ComplianceOtelTracer: ~
  App\Complying\Service\ComplianceTracingPolicyEvaluationService:
    decorates: 'App\Complying\ServiceInterface\CompliancePolicyEvaluationServiceInterface'
    arguments:
      - '@App\Complying\Service\ComplianceTracingPolicyEvaluationService.inner'
      - '@App\Complying\Service\ComplianceOtelTracer'
