version: '3.8'
services:
  compliance-app:
    build: ./docker/compliance
    container_name: compliance-app
    ports:
      - "8081:9000"
    environment:
      APP_ENV: dev
      DATABASE_URL: "pgsql://symfony:symfony@compliance-db:5432/symfony?serverVersion=15&charset=utf8"
    depends_on:
      - compliance-db

  compliance-db:
    image: postgres:15-alpine
    container_name: compliance-db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5445:5432"
    volumes:
      - compliance-db-data:/var/lib/postgresql/data

volumes:
  compliance-db-data: {}
