compliance_cases:
  path: /compliance/cases
  controller: App\Complying\Controller\ComplianceCaseController::list
  methods: [GET]

compliance_case_close:
  path: /compliance/cases/close/{id}
  controller: App\Complying\Controller\ComplianceCaseController::close
  methods: [POST]
