compliance_config_list:
  path: /compliance/config
  controller: App\Complying\Controller\ComplianceConfigController::list
  methods: [GET]

compliance_config_get:
  path: /compliance/config/{slug}
  controller: App\Complying\Controller\ComplianceConfigController::get
  methods: [GET]

compliance_config_put:
  path: /compliance/config/{slug}
  controller: App\Complying\Controller\ComplianceConfigController::set
  methods: [PUT, POST]
