<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Platforms\SQLitePlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Initial cross-platform schema baseline derived from canonical ORM metadata.
 */
final class Version20260912205828 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial Complying schema baseline derived from canonical ORM metadata for PostgreSQL and SQLite.';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();

        if ($platform instanceof PostgreSQLPlatform) {
            $sql = [
                'CREATE TABLE aml_screening (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vendor_id INT NOT NULL, result VARCHAR(24) NOT NULL, hits JSON DEFAULT NULL, screened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))',
                'CREATE TABLE compliance_audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(64) NOT NULL, actor VARCHAR(64) DEFAULT NULL, ip VARCHAR(64) DEFAULT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))',
                'CREATE INDEX idx_compliance_audit_log_action ON compliance_audit_log (action)',
                'CREATE TABLE compliance_case_queue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payload JSON NOT NULL, object_id VARCHAR(64) DEFAULT NULL, tenant_id VARCHAR(64) DEFAULT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, decision_id INT DEFAULT NULL, PRIMARY KEY (id))',
                'CREATE INDEX idx_compliance_case_queue_status ON compliance_case_queue (status)',
                'CREATE INDEX idx_compliance_case_queue_tenant ON compliance_case_queue (tenant_id)',
                'CREATE INDEX IDX_733A001BDEE7539 ON compliance_case_queue (decision_id)',
                'CREATE TABLE compliance_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key_name VARCHAR(128) NOT NULL, value TEXT DEFAULT NULL, scope VARCHAR(128) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))',
                'CREATE UNIQUE INDEX uniq_compliance_config_key_name ON compliance_config (key_name)',
                'CREATE TABLE compliance_decision_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_name VARCHAR(128) NOT NULL, policy_id VARCHAR(64) DEFAULT NULL, policy_version VARCHAR(64) DEFAULT NULL, outcome VARCHAR(32) NOT NULL, facts JSON NOT NULL, object_id VARCHAR(128) DEFAULT NULL, tenant_id VARCHAR(64) DEFAULT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))',
                'CREATE INDEX idx_compliance_decision_log_outcome ON compliance_decision_log (outcome)',
                'CREATE INDEX idx_compliance_decision_log_tenant ON compliance_decision_log (tenant_id)',
                'CREATE INDEX idx_compliance_decision_log_decided_at ON compliance_decision_log (decided_at)',
                'CREATE TABLE compliance_decision_log_archive (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))',
                'CREATE TABLE fraud_signal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vendor_id INT NOT NULL, type VARCHAR(48) NOT NULL, score NUMERIC(6, 2) NOT NULL, context JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))',
                'CREATE TABLE compliance_incident_webhook (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payload TEXT NOT NULL, url VARCHAR(255) NOT NULL, attempts SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))',
                'CREATE TABLE kyc_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vendor_id INT NOT NULL, status VARCHAR(24) NOT NULL, data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))',
                'CREATE TABLE limit_policy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vendor_id INT NOT NULL, daily_limit_minor BIGINT NOT NULL, monthly_limit_minor BIGINT NOT NULL, PRIMARY KEY (id))',
                'CREATE TABLE compliance_policy_registry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, policy_id VARCHAR(128) NOT NULL, policy_version VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, source VARCHAR(32) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))',
                'CREATE UNIQUE INDEX uniq_compliance_policy_registry_policy ON compliance_policy_registry (policy_id)',
                'CREATE TABLE compliance_retention_policy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, resource VARCHAR(120) NOT NULL, days INT NOT NULL, PRIMARY KEY (id))',
                'CREATE TABLE risk_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_entity VARCHAR(64) NOT NULL, dsl TEXT NOT NULL, score NUMERIC(6, 2) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))',
                'CREATE TABLE compliance_sanction_list_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_entity VARCHAR(255) NOT NULL, list_source VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))',
                'ALTER TABLE compliance_case_queue ADD CONSTRAINT FK_733A001BDEE7539 FOREIGN KEY (decision_id) REFERENCES compliance_decision_log (id) ON DELETE SET NULL NOT DEFERRABLE',
            ];
        } elseif ($platform instanceof SQLitePlatform) {
            $sql = [
                'CREATE TABLE aml_screening (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, vendor_id INTEGER NOT NULL, result VARCHAR(24) NOT NULL, hits CLOB DEFAULT NULL, screened_at DATETIME NOT NULL)',
                'CREATE TABLE compliance_audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "action" VARCHAR(64) NOT NULL, actor VARCHAR(64) DEFAULT NULL, ip VARCHAR(64) DEFAULT NULL, payload CLOB NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL)',
                'CREATE INDEX idx_compliance_audit_log_action ON compliance_audit_log ("action")',
                'CREATE TABLE compliance_case_queue (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, payload CLOB NOT NULL, object_id VARCHAR(64) DEFAULT NULL, tenant_id VARCHAR(64) DEFAULT NULL, processed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, modified_at DATETIME DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT 1 NOT NULL, enabled BOOLEAN DEFAULT 1 NOT NULL, status VARCHAR(64) DEFAULT NULL, decision_id INTEGER DEFAULT NULL, CONSTRAINT FK_733A001BDEE7539 FOREIGN KEY (decision_id) REFERENCES compliance_decision_log (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)',
                'CREATE INDEX idx_compliance_case_queue_status ON compliance_case_queue (status)',
                'CREATE INDEX idx_compliance_case_queue_tenant ON compliance_case_queue (tenant_id)',
                'CREATE INDEX IDX_733A001BDEE7539 ON compliance_case_queue (decision_id)',
                'CREATE TABLE compliance_config (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, key_name VARCHAR(128) NOT NULL, value CLOB DEFAULT NULL, scope VARCHAR(128) DEFAULT NULL, created_at DATETIME NOT NULL, modified_at DATETIME DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL)',
                'CREATE UNIQUE INDEX uniq_compliance_config_key_name ON compliance_config (key_name)',
                'CREATE TABLE compliance_decision_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, event_name VARCHAR(128) NOT NULL, policy_id VARCHAR(64) DEFAULT NULL, policy_version VARCHAR(64) DEFAULT NULL, outcome VARCHAR(32) NOT NULL, facts CLOB NOT NULL, object_id VARCHAR(128) DEFAULT NULL, tenant_id VARCHAR(64) DEFAULT NULL, decided_at DATETIME NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL)',
                'CREATE INDEX idx_compliance_decision_log_outcome ON compliance_decision_log (outcome)',
                'CREATE INDEX idx_compliance_decision_log_tenant ON compliance_decision_log (tenant_id)',
                'CREATE INDEX idx_compliance_decision_log_decided_at ON compliance_decision_log (decided_at)',
                'CREATE TABLE compliance_decision_log_archive (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, payload CLOB NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL)',
                'CREATE TABLE fraud_signal (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, vendor_id INTEGER NOT NULL, type VARCHAR(48) NOT NULL, score NUMERIC(6, 2) NOT NULL, context CLOB DEFAULT NULL, created_at DATETIME NOT NULL)',
                'CREATE TABLE compliance_incident_webhook (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, payload CLOB NOT NULL, url VARCHAR(255) NOT NULL, attempts SMALLINT NOT NULL, created_at DATETIME NOT NULL)',
                'CREATE TABLE kyc_profile (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, vendor_id INTEGER NOT NULL, status VARCHAR(24) NOT NULL, data CLOB DEFAULT NULL, created_at DATETIME NOT NULL)',
                'CREATE TABLE limit_policy (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, vendor_id INTEGER NOT NULL, daily_limit_minor BIGINT NOT NULL, monthly_limit_minor BIGINT NOT NULL)',
                'CREATE TABLE compliance_policy_registry (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, policy_id VARCHAR(128) NOT NULL, policy_version VARCHAR(64) NOT NULL, description CLOB DEFAULT NULL, source VARCHAR(32) DEFAULT NULL, created_at DATETIME NOT NULL, modified_at DATETIME DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL)',
                'CREATE UNIQUE INDEX uniq_compliance_policy_registry_policy ON compliance_policy_registry (policy_id)',
                'CREATE TABLE compliance_retention_policy (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, resource VARCHAR(120) NOT NULL, days INTEGER NOT NULL)',
                'CREATE TABLE risk_rule (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name_entity VARCHAR(64) NOT NULL, dsl CLOB NOT NULL, score NUMERIC(6, 2) NOT NULL, active BOOLEAN NOT NULL)',
                'CREATE TABLE compliance_sanction_list_entry (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name_entity VARCHAR(255) NOT NULL, list_source VARCHAR(64) DEFAULT NULL)',
            ];
        } else {
            $this->abortIf(true, sprintf('Unsupported database platform: %s', $platform::class));

            return;
        }

        foreach ($sql as $statement) {
            $this->addSql($statement);
        }
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE aml_screening');
        $this->addSql('DROP TABLE compliance_audit_log');
        $this->addSql('DROP TABLE compliance_case_queue');
        $this->addSql('DROP TABLE compliance_config');
        $this->addSql('DROP TABLE compliance_decision_log');
        $this->addSql('DROP TABLE compliance_decision_log_archive');
        $this->addSql('DROP TABLE compliance_incident_webhook');
        $this->addSql('DROP TABLE compliance_policy_registry');
        $this->addSql('DROP TABLE compliance_retention_policy');
        $this->addSql('DROP TABLE compliance_sanction_list_entry');
        $this->addSql('DROP TABLE fraud_signal');
        $this->addSql('DROP TABLE kyc_profile');
        $this->addSql('DROP TABLE limit_policy');
        $this->addSql('DROP TABLE risk_rule');
    }
}
