imports:
  - { resource: compliance_services_autowire.yaml }
  - { resource: packages/framework.yaml }
  - { resource: packages/security.yaml }
  - { resource: packages/doctrine.yaml }
  - { resource: packages/doctrine_migrations.yaml }
  - { resource: packages/twig.yaml }
  - { resource: packages/compliance_core.yaml }
  - { resource: packages/compliance_policy_registry.yaml }
  - { resource: packages/compliance_policy_bridge.yaml }
  - { resource: packages/compliance_policy_expression.yaml }
  - { resource: packages/compliance_role_sync.yaml }
  - { resource: packages/compliance_tenant.yaml }
  - { resource: packages/compliance_hardening.yaml }
  - { resource: packages/compliance_hmac.yaml }
  - { resource: packages/compliance_webhook.yaml }
  - { resource: packages/compliance_privacy_mapper.yaml }
  - { resource: packages/compliance_kernel_iter_3_1.yaml }
  - { resource: packages/compliance_kernel_iter_3_2.yaml }
  - { resource: packages/compliance_kernel_iter_3_3.yaml }
  - { resource: packages/messenger.yaml }
